# Generated by Django 4.2.26 on 2025-11-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Obsah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'Příspěvek',
                'verbose_name_plural': 'Příspěvky',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nadpis')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Připnuto')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Zamčeno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Počet zobrazení')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Diskusní vlákno',
                'verbose_name_plural': 'Diskusní vlákna',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
