# Generated by Django 4.2.26 on 2025-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='h5p_path',
            field=models.CharField(blank=True, help_text='Relativní cesta k rozbalenému H5P obsahu (např. h5p/quiz-14/)', max_length=255, null=True, verbose_name='Cesta k H5P obsahu'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h5p_embed_code',
            field=models.TextField(blank=True, help_text='Vložte iframe kód pro H5P obsah (starší způsob)', null=True, verbose_name='H5P embed kód'),
        ),
    ]
