# Generated by Django 4.2.26 on 2025-11-29 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Např. 4.A, Skupina A, Třída 2024', max_length=100, verbose_name='Název třídy')),
                ('description', models.TextField(blank=True, help_text='Volitelný popis třídy', null=True, verbose_name='Popis')),
                ('school_year', models.CharField(blank=True, help_text='Např. 2024/2025', max_length=20, null=True, verbose_name='Školní rok')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, help_text='Studenti v této třídě', limit_choices_to={'role': 'student'}, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Studenti')),
                ('teacher', models.ForeignKey(help_text='Učitel, který spravuje tuto třídu', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='Učitel')),
            ],
            options={
                'verbose_name': 'Třída',
                'verbose_name_plural': 'Třídy',
                'ordering': ['name'],
            },
        ),
    ]
