# Generated by Django 4.2.26 on 2025-11-14 20:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Název předmětu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název okruhu')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL slug')),
                ('description', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Popis okruhu')),
                ('order', models.PositiveIntegerField(default=0, help_text='Pořadí zobrazení okruhu', verbose_name='Pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.subject', verbose_name='Předmět')),
            ],
            options={
                'verbose_name': 'Okruh',
                'verbose_name_plural': 'Okruhy',
                'ordering': ['order', 'name'],
                'unique_together': {('subject', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('paragraph', 0), ('h5p_content', 1), ('image', 2), ('document', 3), ('video', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3'], 'label': 'Odstavec'}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Vložte iframe kód pro H5P obsah', 'label': 'H5P obsah'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Obrázek'}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Dokument'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL videa (YouTube, Vimeo, atd.)', 'label': 'Video URL'})}, verbose_name='Obsah')),
                ('topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='subjects.topic', verbose_name='Okruh')),
            ],
            options={
                'verbose_name': 'Stránka okruhu',
                'verbose_name_plural': 'Stránky okruhů',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Popis předmětu')),
                ('subject', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='subjects.subject', verbose_name='Předmět')),
            ],
            options={
                'verbose_name': 'Stránka předmětu',
                'verbose_name_plural': 'Stránky předmětů',
            },
            bases=('wagtailcore.page',),
        ),
    ]
