# Generated by Django 4.2.26 on 2025-11-14 20:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název testu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('h5p_embed_code', models.TextField(blank=True, help_text='Vložte iframe kód pro H5P test', null=True, verbose_name='H5P embed kód')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Prázdné = bez limitu', null=True, verbose_name='Časový limit (minuty)')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='Maximální počet pokusů')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Procentuální úspěšnost pro úspěch')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testy',
                'ordering': ['topic', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Skóre (%)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Úspěšně dokončeno')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dokončeno')),
                ('answers_data', models.JSONField(blank=True, null=True, verbose_name='Data odpovědí')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Pokus o test',
                'verbose_name_plural': 'Pokusy o testy',
                'ordering': ['-started_at'],
            },
        ),
    ]
