# Generated by Django 4.2.26 on 2025-11-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='h5p_path',
            field=models.CharField(blank=True, help_text='Relativní cesta k rozbalenému H5P obsahu (např. h5p/quiz-1/)', max_length=255, null=True, verbose_name='Cesta k H5P obsahu'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='h5p_embed_code',
            field=models.TextField(blank=True, help_text='Vložte iframe kód pro H5P test (starší způsob)', null=True, verbose_name='H5P embed kód'),
        ),
        migrations.CreateModel(
            name='H5PUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(help_text='Unikátní identifikátor H5P obsahu', max_length=100, verbose_name='ID H5P obsahu')),
                ('data', models.JSONField(help_text='JSON data s uloženým stavem uživatele', verbose_name='Data stavu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h5p_user_data', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'H5P uživatelská data',
                'verbose_name_plural': 'H5P uživatelská data',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'content_id')},
            },
        ),
    ]
