# Generated by Django 4.2.26 on 2025-11-29 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID objektu')),
                ('text', models.TextField(help_text='Napište svou připomínku nebo zpětnou vazbu', verbose_name='Text připomínky')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Upraveno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('subject', 'topic')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Typ obsahu')),
            ],
            options={
                'verbose_name': 'Připomínka',
                'verbose_name_plural': 'Připomínky',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='subjects_fe_content_3cd5eb_idx')],
            },
        ),
    ]
