# Generated by Django 4.2.26 on 2025-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentclass'),
        ('subjects', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Třídy, které mají přístup k tomuto předmětu', related_name='subjects', to='accounts.studentclass', verbose_name='Třídy'),
        ),
    ]
