# Generated by Django 4.2.26 on 2025-11-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název materiálu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF dokument'), ('video', 'Video'), ('link', 'Odkaz'), ('h5p', 'H5P interaktivní obsah'), ('text', 'Textový materiál'), ('image', 'Obrázek')], max_length=20, verbose_name='Typ materiálu')),
                ('external_url', models.URLField(blank=True, help_text='URL pro video, odkaz nebo H5P obsah', null=True, verbose_name='Externí URL')),
                ('h5p_embed_code', models.TextField(blank=True, help_text='Vložte iframe kód pro H5P obsah', null=True, verbose_name='H5P embed kód')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Textový obsah')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_materials', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='wagtaildocs.document', verbose_name='Dokument')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='wagtailimages.image', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Materiál',
                'verbose_name_plural': 'Materiály',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
    ]
